language: cpp
sudo: false  # docker VM
git:
  depth: 99999
cache:
  directories:
  - libdeps
matrix:
  include:
  - os: linux
    dist: xenial
    install:
      - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.deb
      - sudo dpkg -i /tmp/hugo.deb
script: ./travis-hugo.sh
notifications:
  email:
    recipients:
      - radarsat1@gmail.com
    on_success: never
    on_failure: change
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: hugosite
    local-dir: pages
    target-branch: gh-pages
    verbose: true
